name: cars
description: A new Flutter project.

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-401.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  smooth_page_indicator:
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  get:
  equatable:
  getwidget: ^3.1.1
  flutter_multi_select_items: ^0.4.2
  select_card: ^0.0.9
  banner_carousel:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DINNextLTW23
      fonts:
        - asset: assets/fonts/din-next-lt-w23-regular.ttf
#        - asset: asstest/fonts/DINNextLTW23-Light.otf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
